package scaffold

import (
	"strings"
	"testing"
)

func TestMarshalCompose_BasicAppService(t *testing.T) {
	spec := ComposeSpec{
		Services: []ServiceSpec{
			{
				Name: "app",
				Build: &BuildSpec{
					Context:    ".",
					Dockerfile: "Dockerfile.streams",
				},
				Ports: []PortMapping{
					{Host: "${STREAMS_PORT}", Container: 3000},
				},
				Volumes: []string{".:/app"},
				Environment: map[string]string{
					"RAILS_ENV": "development",
				},
				Command: "bin/rails server -b 0.0.0.0",
			},
		},
	}

	out, err := MarshalCompose(spec)
	if err != nil {
		t.Fatal(err)
	}

	assertContains(t, out, "services:")
	assertContains(t, out, "app:")
	assertContains(t, out, "dockerfile: Dockerfile.streams")
	assertContains(t, out, "${STREAMS_PORT}:3000")
	assertContains(t, out, ".:/app")
	assertContains(t, out, "RAILS_ENV: development")
	assertContains(t, out, "bin/rails server -b 0.0.0.0")
	assertContains(t, out, "# Generated by streams")
}

func TestMarshalCompose_WithDependencies(t *testing.T) {
	spec := ComposeSpec{
		Services: []ServiceSpec{
			{
				Name:  "db",
				Image: "postgres:16",
				Environment: map[string]string{
					"POSTGRES_PASSWORD": "password",
				},
				HealthCheck: &HealthCheckSpec{
					Test:     []string{"CMD-SHELL", "pg_isready -U postgres"},
					Interval: "5s",
					Timeout:  "5s",
					Retries:  5,
				},
			},
			{
				Name: "app",
				Build: &BuildSpec{
					Context:    ".",
					Dockerfile: "Dockerfile.streams",
				},
				DependsOn: map[string]DependCondition{
					"db": {Condition: "service_healthy"},
				},
			},
		},
	}

	out, err := MarshalCompose(spec)
	if err != nil {
		t.Fatal(err)
	}

	assertContains(t, out, "postgres:16")
	assertContains(t, out, "healthcheck:")
	assertContains(t, out, "pg_isready")
	assertContains(t, out, "service_healthy")
}

func TestMarshalCompose_EmptySpec(t *testing.T) {
	spec := ComposeSpec{}
	out, err := MarshalCompose(spec)
	if err != nil {
		t.Fatal(err)
	}

	assertContains(t, out, "services:")
	assertContains(t, out, "# Generated by streams")
}

func TestMarshalCompose_MultipleServices(t *testing.T) {
	spec := ComposeSpec{
		Services: []ServiceSpec{
			{Name: "app", Build: &BuildSpec{Context: ".", Dockerfile: "Dockerfile.streams"}},
			{Name: "db", Image: "postgres:16"},
			{Name: "redis", Image: "redis:7-alpine"},
		},
	}

	out, err := MarshalCompose(spec)
	if err != nil {
		t.Fatal(err)
	}

	assertContains(t, out, "app:")
	assertContains(t, out, "db:")
	assertContains(t, out, "redis:")
	assertContains(t, out, "redis:7-alpine")
}

func assertContains(t *testing.T, haystack, needle string) {
	t.Helper()
	if !strings.Contains(haystack, needle) {
		t.Errorf("expected output to contain %q, got:\n%s", needle, haystack)
	}
}
