package scaffold

import (
	"bytes"
	"fmt"

	"gopkg.in/yaml.v3"
)

// ComposeSpec is the intermediate representation of a Docker Compose file.
type ComposeSpec struct {
	Services []ServiceSpec
}

// ServiceSpec describes a single service in the compose file.
type ServiceSpec struct {
	Name        string
	Image       string              // for pre-built services (postgres, redis)
	Build       *BuildSpec          // for app service (nil means use Image)
	Ports       []PortMapping
	Volumes     []string
	Environment map[string]string
	DependsOn   map[string]DependCondition
	HealthCheck *HealthCheckSpec
	Command     string
}

// BuildSpec describes how to build a service image.
type BuildSpec struct {
	Context    string
	Dockerfile string
}

// PortMapping maps a host port to a container port.
type PortMapping struct {
	Host      string // "${STREAMS_PORT}" or a fixed port
	Container int
}

// DependCondition controls when a dependent service starts.
type DependCondition struct {
	Condition string // "service_started" or "service_healthy"
}

// HealthCheckSpec defines a container health check.
type HealthCheckSpec struct {
	Test     []string
	Interval string
	Timeout  string
	Retries  int
}

// DockerfileSpec holds the content for a generated Dockerfile.
type DockerfileSpec struct {
	Content string
}

// GeneratedFiles holds all files produced by the scaffolding agent.
type GeneratedFiles struct {
	Compose     string // docker-compose.streams.yml content
	Dockerfile  string // Dockerfile.streams content
	Environment string // .streams/environment.json content
}

const fileHeader = "# Generated by streams. Edit freely — this file is yours.\n"

// MarshalCompose renders a ComposeSpec as a Docker Compose YAML string.
func MarshalCompose(spec ComposeSpec) (string, error) {
	doc := composeDocument{
		Services: make(map[string]composeService),
	}

	for _, svc := range spec.Services {
		cs := composeService{}

		if svc.Image != "" {
			cs.Image = svc.Image
		}
		if svc.Build != nil {
			cs.Build = &composeBuild{
				Context:    svc.Build.Context,
				Dockerfile: svc.Build.Dockerfile,
			}
		}
		if svc.Command != "" {
			cs.Command = svc.Command
		}

		for _, p := range svc.Ports {
			cs.Ports = append(cs.Ports, fmt.Sprintf("%s:%d", p.Host, p.Container))
		}

		cs.Volumes = svc.Volumes

		if len(svc.Environment) > 0 {
			cs.Environment = svc.Environment
		}

		if len(svc.DependsOn) > 0 {
			cs.DependsOn = make(map[string]composeDependsOn)
			for name, dep := range svc.DependsOn {
				cs.DependsOn[name] = composeDependsOn{Condition: dep.Condition}
			}
		}

		if svc.HealthCheck != nil {
			cs.HealthCheck = &composeHealthCheck{
				Test:     svc.HealthCheck.Test,
				Interval: svc.HealthCheck.Interval,
				Timeout:  svc.HealthCheck.Timeout,
				Retries:  svc.HealthCheck.Retries,
			}
		}

		doc.Services[svc.Name] = cs
	}

	var buf bytes.Buffer
	buf.WriteString(fileHeader)

	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return "", fmt.Errorf("marshal compose: %w", err)
	}
	if err := enc.Close(); err != nil {
		return "", fmt.Errorf("marshal compose: %w", err)
	}

	return buf.String(), nil
}

// composeDocument is the YAML-serializable structure for docker-compose.
type composeDocument struct {
	Services map[string]composeService `yaml:"services"`
}

type composeService struct {
	Image       string                        `yaml:"image,omitempty"`
	Build       *composeBuild                 `yaml:"build,omitempty"`
	Command     string                        `yaml:"command,omitempty"`
	Ports       []string                      `yaml:"ports,omitempty"`
	Volumes     []string                      `yaml:"volumes,omitempty"`
	Environment map[string]string             `yaml:"environment,omitempty"`
	DependsOn   map[string]composeDependsOn   `yaml:"depends_on,omitempty"`
	HealthCheck *composeHealthCheck           `yaml:"healthcheck,omitempty"`
}

type composeBuild struct {
	Context    string `yaml:"context"`
	Dockerfile string `yaml:"dockerfile"`
}

type composeDependsOn struct {
	Condition string `yaml:"condition"`
}

type composeHealthCheck struct {
	Test     []string `yaml:"test"`
	Interval string   `yaml:"interval"`
	Timeout  string   `yaml:"timeout"`
	Retries  int      `yaml:"retries"`
}
